---
- hosts: localhost
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: "{{lookup('env', 'resource_grpname')}}"
        location: eastus
      register: rg
    - debug:
        var: rg
